version: '3'
networks:
  cinehub_network:

services:

  java_core:
    build:
      context: .
      dockerfile: Dockerfile
    image: cinehub_core:latest
    ports:
      - "8080:8080"
    depends_on:
      - cinehub_db
      - redis_db
    env_file:
      - java-core.env
    networks:
      - cinehub_network

  cinehub_db:
    image: postgres:latest
    env_file:
      - db.env
    ports:
      - "5432:5432"
    networks:
      - cinehub_network
  redis_db:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - cinehub_network